#Server Configuration
server:
 port: 8085
 
#Logging Configuration
logging:
  level:
    org:
      springframework: info
    com:
      bugtracking: debug
  file:
    name: bugtrackingapi.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
#SQL Query's visible'
spring:
  jpa:
    show-sql: true
    