#Server Configuration
server:
 port: 8085
 
#Logging Configuration
logging:
  level:
    org:
      springframework: info
    com:
      bugtracking: debug
  file:
    name: bugtrackingapi.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
#SQL Query's visible'


spring:
 application:
   name: bugtracker

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
         defaultZone: http://localhost:8761/eureka
  instance: 
    hostname: localhost       
